-- !!! USE ONLY IN CASE OF EMERGENCY
DROP TABLE VEHICLE CASCADE CONSTRAINTS PURGE;
DROP TABLE DRIVER CASCADE CONSTRAINTS PURGE;
DROP TABLE ROUTE CASCADE CONSTRAINTS PURGE;
DROP TABLE PASSENGERS CASCADE CONSTRAINTS PURGE;
DROP TABLE TRIP CASCADE CONSTRAINTS PURGE;
DROP TABLE TICKET CASCADE CONSTRAINTS PURGE;
DROP TABLE PAYMENT CASCADE CONSTRAINTS PURGE;
DROP TABLE MAINTENANCE CASCADE CONSTRAINTS PURGE;

CREATE TABLE VEHICLE (
    vehicle_id NUMBER PRIMARY KEY,
    vehicle_type VARCHAR2(30),
    license_number VARCHAR2(20),
    available_seats NUMBER,
    status VARCHAR2(20)
);
CREATE TABLE DRIVER (
    driver_id NUMBER PRIMARY KEY,
    driver_name VARCHAR2(100),
    contact VARCHAR2(20),
    status VARCHAR2(20)
);
CREATE TABLE ROUTE (
    route_id NUMBER PRIMARY KEY,
    start_location VARCHAR2(100),
    destination VARCHAR2(100)
);
CREATE TABLE PASSENGER (
    passenger_id NUMBER PRIMARY KEY,
    passenger_name VARCHAR2(100),
    contact VARCHAR2(20)
);
CREATE TABLE TRIP (
    trip_id NUMBER PRIMARY KEY,
    route_id NUMBER REFERENCES ROUTE(route_id),
    vehicle_id NUMBER REFERENCES VEHICLE(vehicle_id),
    driver_id NUMBER REFERENCES DRIVER(driver_id),
    trip_date DATE,
    status VARCHAR2(20)
);
CREATE TABLE TICKET (
    ticket_id NUMBER PRIMARY KEY,
    trip_id NUMBER REFERENCES TRIP(trip_id),
    passenger_id NUMBER REFERENCES PASSENGER(passenger_id),
    seat_no VARCHAR2(10),
    booking_date DATE,
    status VARCHAR2(20)
);
CREATE TABLE PAYMENT (
    payment_id NUMBER PRIMARY KEY,
    ticket_id NUMBER REFERENCES TICKET(ticket_id),
    amount NUMBER(10,2),
    payment_date DATE
);
CREATE TABLE MAINTENANCE (
    maintenance_id NUMBER PRIMARY KEY,
    vehicle_id NUMBER REFERENCES VEHICLE(vehicle_id),
    maintenance_date DATE,
    maintenance_type VARCHAR2(50),
    cost NUMBER(10,2),
    next_due_date DATE
);
-- insertion
INSERT INTO VEHICLE VALUES (1, 'Bus', 'V001', 40, 'Active');
INSERT INTO VEHICLE VALUES (2, 'Van', 'V002', 15, 'Active');
INSERT INTO VEHICLE VALUES (3, 'Bus', 'V003', 40, 'Under Maintenance');

INSERT INTO DRIVER VALUES (1, 'John', '0771234567', 'Active');
INSERT INTO DRIVER VALUES (2, 'Amara', '0779876543', 'Active');
INSERT INTO DRIVER VALUES (3, 'Ravi', '0775551234', 'Active');

INSERT INTO ROUTE VALUES (1, 'Colombo', 'Kandy');
INSERT INTO ROUTE VALUES (2, 'Colombo', 'Galle');
INSERT INTO ROUTE VALUES (3, 'Kandy', 'Jaffna');

INSERT INTO PASSENGER VALUES (1, 'Thevan', '0711112222');
INSERT INTO PASSENGER VALUES (2, 'Roosara', '0701163365');
INSERT INTO PASSENGER VALUES (3, 'Gaveen', '0715556666');
INSERT INTO PASSENGER VALUES (4, 'Mona', '0717778888');

INSERT INTO TRIP VALUES (1, 1, 1, 1, DATE '2026-09-10', 'Completed');
INSERT INTO TRIP VALUES (2, 2, 2, 2, DATE '2026-09-12', 'Completed');
INSERT INTO TRIP VALUES (3, 3, 1, 3, DATE '2026-09-14', 'Completed');
INSERT INTO TRIP VALUES (4, 1, 2, 2, DATE '2026-09-20', 'Scheduled');

INSERT INTO TICKET VALUES (1, 1, 1, 'A1', DATE '2026-09-09', 'Booked');
INSERT INTO TICKET VALUES (2, 2, 2, 'A2', DATE '2026-09-11', 'Booked');
INSERT INTO TICKET VALUES (3, 3, 3, 'A3', DATE '2026-09-13', 'Booked');
INSERT INTO TICKET VALUES (4, 4, 4, 'A4', DATE '2026-09-19', 'Booked');

INSERT INTO PAYMENT VALUES (1, 1, 1200.00, DATE '2026-09-10');
INSERT INTO PAYMENT VALUES (2, 2, 1500.00, DATE '2026-09-12');
INSERT INTO PAYMENT VALUES (3, 3, 2000.00, DATE '2026-09-14');

INSERT INTO MAINTENANCE VALUES (1, 3, DATE '2026-09-05', 'Engine Service', 5000.00, DATE '2026-12-05');
INSERT INTO MAINTENANCE VALUES (2, 1, DATE '2026-08-20', 'Tire Change', 1500.00, DATE '2027-02-20');

